### ISSUE TITLE
Trace services interaction

### ISSUE THREAD

**Issue by dpecos** [jaracil/nexus#11]
Having a SOA infrastructure, makes it really hard to track dependencies between services. So having a way of tracking specific user session activity could be a nice way to discover those.

**Comment by dpecos** [comment]
This could be solved in user-space having a metadata field available.

This metadata will also be useful for other purposes as API versioning or requesting tasks in test mode.

**Comment by rgzr** [comment]
This is being developed in github.com/nayarsystems/sugar:
- Including an @meta.trackid param in tasks that will be chained through all sugar services.
- Including an @meta.testing param in tasks that will make sugar to execute an alternative "testing" method.
