### ISSUE TITLE
Limit number of times a task is sent to a service

### ISSUE THREAD

**Issue by oriolf** [jaracil/nexus#12]
Nowadays, if some task makes a service fail, the task returns to Nexus. If the service is then restarted, the task is sent again to the service, which will fail, repeating the cycle indefinitely.

There would have to be some limit in the number of times a task is sent to a service before it is discarded. When it is, nexus should return some kind of error to the caller.

**Comment by jaracil** [comment]
Hi Oriol.
I have in mind add a TTL (counter) field that holds the number of maximum retries a task could return to queue. The default value for this counter could be 5. And it should be changeable in TaskOpts.
I'll fix it soon.

Thanks

**Comment by rgzr** [comment]
Solved.

commit: 5c87a0f74213a0972bbc8b76bdfeda8de1c2cadd
