### ISSUE TITLE
Create OTPs to relocate current session

### ISSUE THREAD

**Issue by dpecos** [jaracil/nexus#17]
I'd like to login in a platform and then use that session from a different platform, without having to deal with user's real credentials. 

Having the possibility of use of OTPs, I could generate an OTP for the logged in session in first platform and relogin with the OTP from the second one.

**Comment by pho** [comment]
Closed by 97d7c3cae63ff3 adding a modular login system.

This issue is implemented via [https://github.com/nayarsystems/nexus-auth-token](https://github.com/nayarsystems/nexus-auth-token)
