### ISSUE TITLE
Create prioritized task requests

### ISSUE THREAD

**Issue by dpecos** [jaracil/nexus#2]
So a service can handle top priority request first.

Very useful when a service has a long queue of requests to be served, and we need to bring forward a new request over the rest of tasks in the queue.

**Comment by jaracil** [comment]
This is a good enhancement. I'll open a new branch  with this issue.

Thanks.

**Comment by jaracil** [comment]
Done.
Commit: c462683b79557600a6fd0ad36059a4c9ccbe7399
