### ISSUE TITLE
Enable canary release

### ISSUE THREAD

**Issue by oriolf** [jaracil/nexus#20]
It would be interesting for nexus to have the ability to select the proportion of traffic that goes to some worker listening on a path. That way you could enable the [canary release](http://martinfowler.com/bliki/CanaryRelease.html) technique, in which you deploy a new worker, send small amounts of traffic to it at first, and when you're confident that it works as expected, send all traffic to the new worker and shut down the old one.

**Comment by pho** [comment]
I like it, but I dont think we can make a server-side approach to this. From nexus's point of view there are no workers, just a number of pulls being made on a path...

The best alternative I can think of would be setting the number of pulls for the new worker at a really low value, and it should get way less traffic than the old ones

**Comment by pho** [comment]
Im going to close this for now. If there is anything else to discuss feel free to comment and i'll reopen it
