### ISSUE TITLE
Extended "basic" authentication

### ISSUE THREAD

**Issue by dpecos** [jaracil/nexus#21]
For our current use case, it's quite easy (or not hard enough) to copy "production credentials" to a dev environment and connect to nexus using that credentials.

Having whitelists and blacklists associated to a credentials could be quite handy to avoid these kind of problems. Relying only in the well-behaving of a person is risky.

**Comment by pho** [comment]
Per-user whitelist/blacklist has been implemented on 88847ac10aa897d759ad22a113818f4e6e4d833a
