### ISSUE TITLE
Add user and task count methods

### ISSUE THREAD

**Issue by oriolf** [jaracil/nexus#34]
Proposal to add two new methods:

- `user.count`, which returns the total number of users.
- `task.count`, which returns the total number of tasks.

These two methods would be useful when implementing pagination of users and tasks.

**Comment by pho** [comment]
Due to the dynamic nature of Nexus, these count values may change after the response and pagination might not be accurate, but we think it could be useful for some use cases anyway

We'll add `topic.list`, `topic.count`, `sessions.count`, `sync.list`, `sync.count` too

**Comment by rgzr** [comment]
The `*.count` methods accept two optional parameters.

The `prefix` parameter limit the prefixes to count.

The `subprefixes` boolean parameter when set to `true` returns a list of the subprefixes under the prefix provided with the count for each (in addition to the prefix itself), while the default value `false` returns only the count for the prefix provided. The first version allows to "explore" the existing prefixes one level at a time.

This has been implemented in https://github.com/jaracil/nexus/commit/776d225764f13a983e9f66ab975e8ab0da1d0907 and https://github.com/jaracil/nexus/commit/adfa4954a9ecd2179b2b4284a581b704f95b0566
